# Generated by Django 4.0.1 on 2022-02-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_cartitem_variations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="cart_id",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
