# Generated by Django 4.0.1 on 2022-02-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_cartitem_user_alter_cartitem_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="cart_id",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
