# Generated by Django 4.0.1 on 2022-02-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="state",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
