# Generated by Django 4.0.1 on 2022-02-15 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_remove_orderproduct_variation_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderproduct",
            old_name="variations",
            new_name="variation",
        ),
    ]
