# Generated by Django 4.0.1 on 2022-02-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_rename_variations_orderproduct_variation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="state",
            field=models.CharField(max_length=50),
        ),
    ]
