# Generated by Django 4.0.1 on 2022-02-15 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_alter_order_state"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderproduct",
            old_name="variation",
            new_name="variations",
        ),
    ]
